### ISSUE TITLE
Audio content to fix

### ISSUE THREAD

**Issue by DinisCruz** [DinisCruz/keynote-bsideslisbon#2]
Here are the audio transcriptions that need content fixing.

@Ambg05 can you start with these?

* [ Creating a sharing culture](https://github.com/DinisCruz/keynote-bsideslisbon/blob/0a4fc6f8e42aa9e2bc5206f0323c5ccf96eedcae/Articles/to-fix-audio/Creating-a-sharing-culture.md)

**Comment by Ambg05** [comment]
Yes, I'll just finish a file I started on Friday, review #141 as requested and then do this file.
