### ISSUE TITLE
Get info about 'password leaks for .PT companies'

### ISSUE THREAD

**Issue by DinisCruz** [DinisCruz/keynote-bsideslisbon#34]
as per https://twitter.com/Balgan/status/796134153192427520

**Comment by anabarbosa** [comment]
Hi Dinis

here is information for password leaks in Portugal: https://www.dropbox.com/s/vf195gpdil54c24/dataleaks%20PT.html?dl=0

Let me know if you need anything in more detail or more data.

**Comment by DinisCruz** [comment]
Thanks a lot @anabarbosaBE  

I added that info to the slides
